### ISSUE TITLE
Fail to install type-combinators in order to load model.hs

### ISSUE THREAD

**Issue by vincent-hui** [mstksg/inCode#12]
How to load https://github.com/mstksg/inCode/blob/master/code-samples/functional-models/model.hs in ghci?
When I load it. I get the following message
```
model.hs:31:1: error:
    Could not find module ‘Data.Type.Option’
    Perhaps you meant Data.Type.Util
    Use -v to see a list of the files searched for.
   |
31 | import           Data.Type.Option
```
When I install type-combinators by running "cabal install type-combinators". I get the following error
```
src/Type/Family/Nat.hs:65:1: error:
    • Illegal instance for closed family ‘==’
    • In the type instance declaration for ‘==’
   |
65 | type instance x == y = NatEq x y
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to install type-combinators-0.2.4.3
cabal: Error: some packages failed to install:
type-combinators-0.2.4.3-Fh07Kc39xOV2fiSnegBCi4 failed during the building
phase. The exception was:
ExitFailure 1
```

Thank a lot

**Comment by mstksg** [comment]
Ah yeah, this is because the current type-combinators on hackage is incompatible with the latest ghc.  The easiest way to load this into ghci would be to modify line 2 in the file.  I've modified the file slightly to provide an alternative stack script line that pops you into a ghc session instaed.  https://github.com/mstksg/inCode/blob/master/code-samples/functional-models/model.hs should have the new instructions! (on lines 4 and 5)

Let me know if this works :)

**Comment by vincent-hui** [comment]
Thank a lot!
This works for me.

**Comment by mstksg** [comment]
Glad it worked out! :D
